import { db } from '@/lib/db';

export default async function AdminTicketsPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const { status = '' } = await searchParams;
  const allowed = ['open','in_progress','resolved','closed'];
  const filter = allowed.includes(status) ? status : '';
  const { rows } = await db.query(`SELECT t.id,t.subject,t.priority,t.status,t.created_at,t.updated_at,u.full_name,u.email,u.referral_code FROM support_tickets t JOIN users u ON u.id=t.user_id WHERE ($1='' OR t.status=$1) ORDER BY CASE t.priority WHEN 'urgent' THEN 0 WHEN 'high' THEN 1 ELSE 2 END,t.updated_at DESC LIMIT 150`, [filter]);
  return <div><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><h2 className="text-2xl font-bold">Support Tickets</h2><p className="mt-1 text-sm text-slate-400">User support queue with assignment and audit history.</p></div><form><select name="status" defaultValue={filter} className="rounded-xl border border-blue-900/60 bg-[#09172a] px-3 py-2 text-sm" onChange={undefined}><option value="">All statuses</option><option value="open">Open</option><option value="in_progress">In Progress</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select><button className="ml-2 rounded-xl bg-blue-600 px-4 py-2 text-sm">Filter</button></form></div>
    <div className="mt-6 overflow-x-auto rounded-2xl border border-blue-900/50"><table className="min-w-full text-sm"><thead className="bg-blue-950/40 text-left text-slate-400"><tr><th className="p-3">Ticket</th><th className="p-3">User</th><th className="p-3">Priority</th><th className="p-3">Status</th><th className="p-3">Updated</th></tr></thead><tbody>{rows.map((t:any)=><tr key={t.id} className="border-t border-blue-950/70"><td className="p-3"><a href={`/admin/tickets/${t.id}`} className="font-semibold text-blue-300">{t.subject}</a></td><td className="p-3"><div>{t.full_name}</div><div className="text-xs text-slate-500">{t.email} • {t.referral_code}</div></td><td className="p-3 capitalize">{t.priority}</td><td className="p-3 capitalize">{t.status.replace('_',' ')}</td><td className="p-3 text-slate-400">{new Date(t.updated_at).toLocaleString('en-IN')}</td></tr>)}</tbody></table>{!rows.length&&<div className="p-8 text-center text-sm text-slate-500">No tickets found.</div>}</div>
  </div>;
}
